Migrate to Next.js 14 and app directory
upleveled/next-starter-peacock pull request #155
Opened 2023-12-27 10:52 UTC by ProchaLu

This PR migrates the portfolio to Next.js 14 and the app directory structure. It imports the necessary changes from the [original portfolio](https://github.com/vickonrails/next-starter-peacock) and fixes any errors encountered during the process.

2023-12-29 17:50 UTC, karlhorky commented on .vscode/settings.json
> +  "git.ignoreLimitWarning": true
What is this? Do we really want it?

2023-12-29 17:59 UTC, karlhorky requested changes
~Compare the last version of the code in this PR with the version in the vickonrails repo, and create a diff that we can use (eg. copy the code of each file to your editor and then run `git diff` and copy the output to a new comment in the PR)~

Edit: Hm, let's try something else, see below

2023-12-30 01:58 UTC, karlhorky requested changes
It seems like this PR doesn't have any commits from `vickonrails`, which it should have (we need to update our fork to have all of the commits that he made in https://github.com/vickonrails/next-starter-peacock)

Updating from the "upstream" (the https://github.com/vickonrails/next-starter-peacock repo) is done like this:

1. create a fresh new branch off of our `main`
2. copy the Git URL using the green Code button dropdown on https://github.com/vickonrails/next-starter-peacock
3. add a new origin eg. `git remote add vickonrails <paste URL you copied>`
4. pull in the changes `git pull vickonrails master`
5. open a new PR
6. make the necessary changes from this PR in the new PR (eg. fixing TypeScript and ESLint problems)

After you have done this, then check your branch against `vickonrails` using a "compare" link like this (change the `update-next-14` bit at the end to your new branch name):

https://github.com/vickonrails/next-starter-peacock/compare/master...upleveled:next-starter-peacock:update-next-14

2024-01-02 08:53 UTC, ProchaLu commented
Superseded by #156

2024-01-02 08:53 UTC, closed without merging